version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./quero_poke_back/tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  queropoke:
    build: ./quero_poke_back
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./quero_poke_back:/quero_poke_back
    ports:
      - "3000:3000"
    depends_on:
      - db